apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.audit.service }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.audit.service }}
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi({{ .Values.audit.service }})"]
      restartPolicy: Never
  backoffLimit: 4