# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "aws_s3_bucket" "test_2" {
  bucket = "my-bucket"
  tags = {
    Name       = "My bucket"
    Enviroment = "Dev"
  }
}
resource "aws_s3_object" "test_2" {
  bucket = "my-bucket"
  key    = "terraform.tfstate"
  source = "terraform.tfstate"
}
