name: "terraform-deploy"

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{steps.prNamespaceExtraction.outputs.namespace}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export namespace in PR's title namespace
        id: prNamespaceExtraction
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            namespace="dev"
          else
            namespace_detect_pattern="(.*\[ns:)(.+)(:ns\].*)"
            if [[ $namespace =~ $namespace_detect_pattern ]]; then
              namespace=${BASH_REMATCH[2]}
            else
              namespace=""
            fi
          fi
          echo "namespace=$namespace"
          echo "namespace=$namespace" >> $GITHUB_OUTPUT

  automation:
    needs: prepare
    runs-on: ubuntu-latest
    services:
      aws:
        image: localstack/localstack:2.1.0
        env:
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
          AWS_PARAMSTORE_ENABLED: "false"
        ports:
          - 4566:4566

    steps:
      - name: Checkout main branch from Github
        uses: actions/checkout@v2  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: '0.46.3'

      - name: Terragrunt Plan
        run: |
          cd environments/${{ github.prepare.outputs.namespace }}
          terragrunt apply --auto-approve
          ls

      - name: Validate on Localstack
        run: |
          echo "Check new S3 bucket"
          aws --endpoint-url http://localhost:4566 s3api list-buckets
          aws s3api --endpoint-url http://localhost:4566 list-objects --bucket my-bucket --query 'Contents[].{Key: Key, Size: Size}'
        env: 
          AWS_ACCESS_KEY_ID: "test"
          AWS_SECRET_ACCESS_KEY: "test"
          AWS_REGION: "us-east-1"