name: 'Terraform Unit Tests'

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      shell: bash
      run: |

        overwritepath=./${{ inputs.environment }}/${{ inputs.namespace }}/${{ inputs.service_name }}/
